### ISSUE TITLE
fix: repo list only shows up to 30 projects

### ISSUE THREAD

**Issue by MikeCraig418** [lets-make-dev/github-issues-front-end#12]
- [x] Create a Project in the app
- [x] Attach a Github Account having more than 30 repos
- [x] Observe only 30 repos are present

<img width="590" alt="image" src="https://github.com/user-attachments/assets/1f5bb940-0183-420f-a414-3cf3d0ab30f5">

**Comment by digidoers** [comment]
We have increased the per-page limit to 100.

https://docs.github.com/en/rest/apps/installations?apiVersion=2022-11-28
